version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    container_name: app-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./tmp:/app/tmp
    environment:
      - EVALBACKEND_HOST=eval-backend
      - EVALBACKEND_PORT=8080
    restart: always
  eval-backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: eval-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/eval_backend/backend
      - ./tmp:/eval_backend/tmp
    environment:
      - EXECUTION_CONTEXT=DEV
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    restart: always
  chromadb:
    build:
      dockerfile: Dockerfile
      context: ./vectorstore
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./vectorstore/chromadb:/chroma/chroma
      - ./vectorstore:/vectorstore
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    restart: always
