version: "3"
services:
  backend-test:
    image: ragflow-backend:latest
    container_name: backend-test
    ports:
      - "8080:8080"
    environment:
      - CHROMADB_HOST=chromadb-test
      - CHROMADB_PORT=8000
      - EXECUTION_CONTEXT=TEST
      - LOG_LEVEL=INFO
      - INPUT_LABEL_DATASET=./resources/input_label_dataset.json
    volumes:
      - ./resources/tests:/eval_backend/resources
  chromadb-test:
    image: ragflow-vectorstore:latest
    container_name: chromadb-test
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
  test-suite:
    image: ragflow-test:latest
    container_name: tester
    environment:
      - EVALBACKEND_HOST=backend-test
      - EVALBACKEND_PORT=8080
      - CHROMADB_HOST=chromadb-test
      - CHROMADB_PORT=8000
    depends_on:
      - backend-test
      - chromadb-test
    volumes:
      - ./resources/tests:/tests/resources
