version: "3"
services:
  ragflow-test:
    image: andreasx42/ragflow-backend:latest
    container_name: ragflow-test
    ports:
      - "8080:8080"
    environment:
      - CHROMADB_HOST=chromadb-test
      - CHROMADB_PORT=8000
      - EXECUTION_CONTEXT=TEST
      - LOG_LEVEL=INFO
      - INPUT_LABEL_DATASET=./resources/input_label_dataset.json
    volumes:
      - ./resources/tests:/backend/resources
  chromadb-test:
    image: andreasx42/ragflow-vectorstore:latest
    container_name: chromadb-test
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
  test-suite:
    image: andreasx42/ragflow-test:latest
    container_name: tester
    environment:
      - RAGFLOW_HOST=ragflow-test
      - RAGFLOW_PORT=8080
      - CHROMADB_HOST=chromadb-test
      - CHROMADB_PORT=8000
    depends_on:
      - ragflow-test
      - chromadb-test
    volumes:
      - ./resources/tests:/tests/resources
