version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    container_name: app-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./tmp:/app/tmp
    environment:
      - EVALBACKEND_HOST=eval-backend
      - EVALBACKEND_PORT=8080
  eval-backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: eval-backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/eval_backend/backend
      - ./tmp:/eval_backend/tmp
    environment:
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
  chromadb:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb
    volumes:
      - ./vectorstore/chromadb:/chroma/chroma
      - ./vectorstore:/vectorstore
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
  test-suite:
    build:
      dockerfile: Dockerfile
      context: ./tests
    container_name: tester
    environment:
      - EVALBACKEND_HOST=localhost
      - EVALBACKEND_PORT=8080
      - CHROMADB_HOST=localhost
      - CHROMADB_PORT=8000
    depends_on:
      - app
      - eval-backend
      - chromadb
