version: "3"
services:
  backend-test:
    build:
      dockerfile: Dockerfile
      context: ./backend
    container_name: backend-test
    ports:
      - "8080:8080"
    environment:
      - CHROMADB_HOST=chromadb-test
      - CHROMADB_PORT=8000
      - EXECUTION_CONTEXT=TEST
    volumes:
      #    - ./backend:/eval_backend/backend
      - ./resources/tests:/eval_backend/resources
  chromadb-test:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chromadb-test
    ports:
      - 8000:8000
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
  test-suite:
    build:
      dockerfile: Dockerfile
      context: ./tests
    container_name: tester
    environment:
      - EVALBACKEND_HOST=backend-test
      - EVALBACKEND_PORT=8080
      - CHROMADB_HOST=chromadb-test
      - CHROMADB_PORT=8000
    depends_on:
      - backend-test
      - chromadb-test
    volumes:
      - ./resources/tests:/tests/resources
    #    - ./tests:/tests
    #restart: always
