version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    container_name: app-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./tmp:/app/tmp
    environment:
      - RAGFLOW_HOST=ragflow-backend
      - RAGFLOW_PORT=8080
    restart: always
  ragflow-backend:
    build:
      dockerfile: Dockerfile
      context: ./ragflow
    container_name: ragflow-backend
    ports:
      - "8080:8080"
    volumes:
      - ./ragflow:/backend/ragflow
      - ./tmp:/backend/tmp
    environment:
      - JWT_SECRET_KEY=brjia5mOUlE3RN0CFy
      - POSTGRES_DATABASE=postgres_db
      - PGVECTOR_DATABASE=vector_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DRIVER=psycopg2
      - EXECUTION_CONTEXT=DEV
      - LOG_LEVEL=INFO
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    restart: always
  chromadb:
    build:
      dockerfile: Dockerfile
      context: ./vectorstore
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./vectorstore/chroma:/chroma/chroma
      - ./vectorstore:/vectorstore
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    restart: always
  postgres:
    image: ankane/pgvector:v0.5.1
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=my_password
    restart: always
  pgadmin:
    image: dpage/pgadmin4:8.0
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=my_password
    ports:
      - "5050:80"
    restart: always
