version: "3"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: ./app
    container_name: app-frontend
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - ./tmp:/app/tmp
    environment:
      - RAGFLOW_HOST=ragflow-backend
      - RAGFLOW_PORT=8080
    restart: always
  ragflow-backend:
    build:
      dockerfile: Dockerfile
      context: ./ragflow
    container_name: ragflow-backend
    ports:
      - "8080:8080"
    volumes:
      - ./ragflow:/backend/ragflow
      - ./tmp:/backend/tmp
    environment:
      - EXECUTION_CONTEXT=DEV
      - LOG_LEVEL=INFO
      - CHROMADB_HOST=chromadb
      - CHROMADB_PORT=8000
    restart: always
  chromadb:
    build:
      dockerfile: Dockerfile
      context: ./vectorstore
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./vectorstore/chromadb:/chroma/chroma
      - ./vectorstore:/vectorstore
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE
    restart: always
