version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.11
#        environment:
#          FLASK_CONFIG: testing
    steps:
      - checkout
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=python-circleci-docker' >> $BASH_ENV 
            virtualenv venv
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run Tests
          command: |
            . venv/bin/activate
            python tests/test.py
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build and push Docker image
          command: |
            . venv/bin/activate
          #  pyinstaller -F hello_world.py
            docker build -t $DOCKER_USER/$IMAGE_NAME:$TAG ./app
            echo $DOCKER_PWD | docker login -u $DOCKER_LOGIN --password-stdin
            docker push $DOCKER_USER/$IMAGE_NAME:$TAG
      #- run:
      #    name: Deploy app to Digital Ocean Server via Docker
      #    command: |
      #      ssh -o StrictHostKeyChecking=no root@hello.dpunks.org "/bin/bash ./deploy_app.sh #$DOCKER_USER/$IMAGE_NAME:$TAG"
