version: 2.1

executors:
  hosted_node:
    machine:
      image: ubuntu-2004:current
    resource_class: medium
    
jobs:
  build:
    executor: hosted_node
    environment:
       PIPELINE_NUMBER: << pipeline.number >>
    steps:
      - run:
          name: show pipeline number
          command: |
                   echo “pipeline.number <<pipeline.number>>”
                   echo “pipeline.number: $PIPELINE_NUMBER”
        
workflows:
  process:
    jobs:
     - build