apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
  template:
    metadata:
      labels:
        component: frontend
    spec:
      volumes:
        - name: frontend-storage
          persistentVolumeClaim:
            claimName: shared-persistent-volume-claim
      containers:
        - name: app-frontend
          image: andreasx42/ragflow-app:latest
          env:
            - name: EVALBACKEND_HOST
              value: backend-cluster-ip-service
            - name: EVALBACKEND_PORT
              value: '8080'
          ports:
            - containerPort: 8501
          volumeMounts:
            - name: frontend-storage
              mountPath: app/tmp
              subPath: tmp