apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: backend
  template:
    metadata:
      labels:
        component: backend
    spec:
      volumes:
        - name: backend-storage
          persistentVolumeClaim:
            claimName: shared-persistent-volume-claim
      containers:
        - name: ragflow-backend
          image: andreasx42/ragflow-backend:latest
          env:
            - name: CHROMADB_HOST
              value: vectorstore-cluster-ip-service
            - name: CHROMADB_PORT
              value: '8000'
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: backend-storage
              mountPath: backend/tmp
              subPath: tmp