    apiVersion: networking.k8s.io/v1
    # UPDATE API
    kind: Ingress
    metadata:
      name: ingress-service
      annotations:
        nginx.ingress.kubernetes.io/use-regex: 'true'
        # ADD ANNOTATION
        nginx.ingress.kubernetes.io/rewrite-target: /$1
        # UPDATE ANNOTATION
    spec:
      ingressClassName: nginx 
      rules:
        - http:
            paths:
              - path: /?(.*)
                # UPDATE PATH
                pathType: ImplementationSpecific
                # ADD PATHTYPE
                backend:
                  service:
                    # UPDATE SERVICE FIELDS
                    name: app-cluster-ip-service
                    port:
                      number: 8501
              - path: /api/?(.*)
                # UPDATE PATH
                pathType: ImplementationSpecific
                # ADD PATHTYPE
                backend:
                  service:
                    # UPDATE SERVICE FIELDS
                    name: backend-cluster-ip-service
                    port:
                      number: 8080